# Generated by Django 2.1.5 on 2019-02-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='clasyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2nd-year', '2'), ('3rd-year', '3'), ('4th-year', '4')], max_length=100)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
                ('fdescription', models.CharField(blank=True, max_length=50)),
                ('categorie', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='filest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.FileField(upload_to='')),
                ('fdescription', models.CharField(blank=True, max_length=50)),
                ('usn', models.CharField(max_length=50)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileManager.clasyear', to_field='name')),
            ],
        ),
    ]
