# Generated by Django 2.1.5 on 2019-02-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a',
        ),
        migrations.DeleteModel(
            name='files',
        ),
    ]
