# Generated by Django 2.1.8 on 2019-04-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPrep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewexperience',
            old_name='comapanyName',
            new_name='companyName',
        ),
    ]
