# Generated by Django 2.1.8 on 2019-04-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPrep', '0002_auto_20190409_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=None, max_length=500)),
                ('subjectName', models.CharField(max_length=500)),
                ('topicHeading', models.CharField(max_length=500)),
                ('topicDescription', models.CharField(max_length=5000)),
            ],
        ),
    ]
