# Generated by Django 2.1.8 on 2019-04-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPrep', '0003_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.AlterField(
            model_name='subject',
            name='userName',
            field=models.CharField(max_length=500),
        ),
    ]
