# Generated by Django 2.1.8 on 2019-04-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainBoard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aptitude',
        ),
        migrations.DeleteModel(
            name='InterviewExperience',
        ),
        migrations.DeleteModel(
            name='popularCodingProblems',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
