# Generated by Django 2.1.8 on 2019-04-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainBoard', '0003_myprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='myProfile',
        ),
    ]
