# Generated by Django 2.1.8 on 2019-04-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainBoard', '0007_myprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='usersScore',
            field=models.IntegerField(default=0),
        ),
    ]
